minor fixes

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -49,14 +49,15 @@ putResource() {
   response_body=$(mktemp /tmp/response_body.XXXXXX)
   eval "$cmd" > $response_body || exit $1
   cp ${response_body} ${sources_dir}/response_body
-  cat $response_body | jq -e '.message?'
-  if [ $? -eq 0 ]; then
-    echo "--> Failed to create a new GitHub Actions Workflow run via dispatches."
-    echo "Aborting job..."
-    exit 1
-  else
+  message=$(cat ${response_body} | jq -r '.message?')
+  if [ ${#message} -eq 0 ]; then
     echo "--> GitHub Actions Workflow run created using dispatches..."
     cat ${response_body}
+  else
+    echo "--> Failed to create a new GitHub Actions Workflow run via dispatches."
+    echo $message
+    echo "Aborting job..."
+    exit 1
   fi
 
   # Fetching GitHub Actions Workflow run ID
